{% set name = "glearn" %}
{% set data = load_setup_py_data() %}

package:
    name: "{{ name|lower }}"
    version: "{{ data['version'] }}"

source:
    path: ..

# build:
#     number: 0
#     script:
#         - {{ PYTHON }} -m pip install . -vv --no-binary :all:
        # - {{ PYTHON }} -m pip install --upgrade pip setuptools wheel &&
        # - {{ PYTHON }} -m pip install dist/*.whl -vvv  # [osx]
        # - {{ PYTHON }} -m pip install . -vv  # [not osx]
        # - {{ PYTHON }} -m pip install . --single-version-externally-managed --record=record.txt -vvv  # [not osx]
        # - {{ PYTHON }} -m pip install . --single-version-externally-managed --record=record.txt --ignore-installed --no-cache-dir -vvv  # [not osx]
    # script: sh ./build_macos.sh     # [mac]
        # - export CFLAGS="${CFLAGS} -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk"; {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
        # - export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk; {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
        # - export CFLAGS="${CFLAGS} -isysroot ${CONDA_BUILD_SYSROOT}"; {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
    # script: # - python setup.py install . --single-version-externally-managed --record=record.txt -vvv
    # script: {{ PYTHON }} -m pip install . --single-version-externally-managed --record=record.txt --no-deps --ignore-installed --no-cache-dir -vvv
    # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - llvm-openmp  # [osx]
        - python {{ python }}
        - special_functions       # needs -c s-ameli

    host:
        # - python {{ python }}
        - setuptools
        - cython>=0.29,<3.0
        - pip
        - special_functions       # needs -c s-ameli
        - detkit                  # needs -c s-sameli
        - llvm-openmp  # [osx]
    run:
        - python {{ python }}
        - numpy>1.11
        # - {{ pin_compatible('numpy') }}
        - scipy>=1.5
        - matplotlib
        - seaborn
        - imate                   # needs -c s-ameli
        - special_functions       # needs -c s-sameli
        - detkit                  # needs -c s-sameli
        - llvm-openmp  # [osx]

test:
    imports:
        - glearn
    requires:
        - pytest
        - pytest-cov
        - pytest-runner

about:
    home: {{ data['url'] }}
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: {{ data['description'] }}
    description: {{ data['description'] }}
    doc_url: https://ameli.github.io/glearn/index.html
    doc_source_url: https://github.com/ameli/glearn/blob/main/README.rst
    dev_url: https://github.com/ameli/glearn

extra:
    recipe-maintainers:
        - ameli
